cluster:
  name: "LocalHadoopCluster"
  storage:
    type: "hadoop"
    uri: "hdfs://namenode:9000/"
    root-path: "/data/openhouse"
  iceberg:
    write:
      format:
        default: "orc"
      metadata:
        previous-versions-max: 28
        delete-after-commit:
          enabled: true
  housetables:
    base-uri: "http://openhouse-housetables:8080"
    database:
      type: "IN_MEMORY"
  security:
    token:
      interceptor:
        classname: "com.linkedin.openhouse.common.security.DummyTokenInterceptor"
    tables:
      authorization:
        enabled: true
