cluster:
  name: "LocalFSCluster"
  storage:
    type: "hadoop"
    uri: "hdfs://namenode:9000/"
    root-path: "/data/openhouse"
  storages:
    default-type: "s3"
    types:
      s3:
        rootpath: "openhouse-bucket"
        endpoint: "s3://"
        parameters:
          s3.endpoint: "http://minioS3:9000"
          s3.access-key-id: "admin"
          s3.secret-access-key: "password"
          s3.path-style-access: true
  iceberg:
    write:
      format:
        default: "orc"
      metadata:
        previous-versions-max: 28
        delete-after-commit:
          enabled: true
  housetables:
    base-uri: "http://openhouse-housetables:8080"
    database:
      type: "MYSQL"
      url: "jdbc:mysql://mysql:3306/oh_db?allowPublicKeyRetrieval=true&useSSL=false"
  security:
    token:
      interceptor:
        classname: "com.linkedin.openhouse.common.security.DummyTokenInterceptor"
    tables:
      authorization:
        enabled: true
        opa:
          base-uri: "http://opa:8181"
